// Exact-match dictionary for the DOM auto-translator.
// Add more entries any time — key must match the visible English text EXACTLY (case-sensitive, trimmed).
export const autoDict: Record<string, string> = {
  // Common nav / breadcrumbs
  'Home': 'होम',
  'Dashboard': 'डैशबोर्ड',

  // Common buttons
  'Save': 'सहेजें',
  'Cancel': 'रद्द करें',
  'Submit': 'जमा करें',
  'Reset': 'रीसेट',
  'Edit': 'संपादित करें',
  'Delete': 'हटाएं',
  'Close': 'बंद करें',
  'Apply': 'लागू करें',
  'Export CSV': 'सीएसवी निर्यात करें',
  'Log in': 'लॉग इन',
  'Logging in…': 'लॉग इन हो रहा है…',
  'Sign out': 'साइन आउट',
  'Accept': 'स्वीकार करें',
  'Reject': 'अस्वीकार करें',
  'Add': 'जोड़ें',
  'Add Technician': 'तकनीशियन जोड़ें',
  'Add Dealer': 'डीलर जोड़ें',
  'Add Item': 'आइटम जोड़ें',
  'Adding...': 'जोड़ा जा रहा है...',
  'Saving...': 'सहेजा जा रहा है...',
  'Confirm delivery': 'डिलीवरी की पुष्टि करें',
  'Confirming...': 'पुष्टि हो रही है...',
  'Verify & deliver →': 'सत्यापित करें और डिलीवर करें →',
  'Generate delivery OTP': 'डिलीवरी ओटीपी जनरेट करें',
  'Generating...': 'जनरेट हो रहा है...',
  'Clear signature': 'हस्ताक्षर साफ़ करें',
  '+ Add Technician': '+ तकनीशियन जोड़ें',
  '+ Add Dealer': '+ डीलर जोड़ें',
  '+ Add Item': '+ आइटम जोड़ें',
  '+ New claim': '+ नया दावा',
  '+ Upload file': '+ फ़ाइल अपलोड करें',

  // Status / labels
  'Status': 'स्थिति',
  'Active': 'सक्रिय',
  'Inactive': 'निष्क्रिय',
  'All Status': 'सभी स्थिति',
  'Activate': 'सक्रिय करें',
  'Deactivate': 'निष्क्रिय करें',
  'Loading...': 'लोड हो रहा है...',
  'Name': 'नाम',
  'Phone': 'फ़ोन',
  'Email': 'ईमेल',
  'Role': 'भूमिका',
  'Joined': 'शामिल हुए',
  'Actions': 'कार्रवाई',
  'Details': 'विवरण',
  'Action': 'कार्रवाई',

  // Table / list generic
  'All Technicians': 'सभी तकनीशियन',
  'All Dealers': 'सभी डीलर',
  'All Users': 'सभी उपयोगकर्ता',
  'All Inventory Items': 'सभी इन्वेंटरी आइटम',
  'All job cards': 'सभी जॉब कार्ड',
  'All warranty claims': 'सभी वारंटी दावे',
  'No technicians match your search.': 'आपकी खोज से कोई तकनीशियन मेल नहीं खाता।',
  'No dealers match your search.': 'आपकी खोज से कोई डीलर मेल नहीं खाता।',
  'No users found.': 'कोई उपयोगकर्ता नहीं मिला।',
  'No items match your search.': 'आपकी खोज से कोई आइटम मेल नहीं खाता।',
  'No job cards found.': 'कोई जॉब कार्ड नहीं मिला।',
  'No claims match your search.': 'आपकी खोज से कोई दावा मेल नहीं खाता।',
  'No vehicles found.': 'कोई वाहन नहीं मिला।',

  // Forms
  'Full Name *': 'पूरा नाम *',
  'Phone *': 'फ़ोन *',
  'Email (optional)': 'ईमेल (वैकल्पिक)',
  'Password *': 'पासवर्ड *',
  'Dealer Name *': 'डीलर का नाम *',
  'City *': 'शहर *',
  'Address': 'पता',
  'Search by name or phone...': 'नाम या फ़ोन से खोजें...',
  'Search by dealer name or city...': 'डीलर नाम या शहर से खोजें...',
  'Search by name, email, or phone...': 'नाम, ईमेल या फ़ोन से खोजें...',
  'Search by part name or code...': 'पार्ट नाम या कोड से खोजें...',
  'Search job cards...': 'जॉब कार्ड खोजें...',
  'Search claims...': 'दावे खोजें...',

  // Job card / warranty specific
  'Registered': 'पंजीकृत',
  'Acknowledged': 'स्वीकृत',
  'Rejected': 'अस्वीकृत',
  'Technician assigned': 'तकनीशियन नियुक्त',
  'In progress': 'प्रगति में',
  'Completed': 'पूर्ण',
  'Delivered': 'डिलीवर हो गया',
  'Normal': 'सामान्य',
  'Urgent': 'तत्काल',
  'Emergency': 'आपातकालीन',
  'Submitted': 'प्रस्तुत',
  'Under review': 'समीक्षा में',
  'Approved': 'स्वीकृत',
  'Resolved': 'हल हो गया',

  // Password change
  'Change Password': 'पासवर्ड बदलें',
  'Current Password *': 'वर्तमान पासवर्ड *',
  'New Password *': 'नया पासवर्ड *',
  'Confirm New Password *': 'नया पासवर्ड की पुष्टि करें *',
  'Update Password': 'पासवर्ड अपडेट करें',
  'Updating...': 'अपडेट हो रहा है...',

  // Misc
  'Loading technicians...': 'तकनीशियन लोड हो रहे हैं...',
  'Loading dealers...': 'डीलर लोड हो रहे हैं...',
  'Loading users...': 'उपयोगकर्ता लोड हो रहे हैं...',
  'Loading claims...': 'दावे लोड हो रहे हैं...',
};

// Page-specific additions: Dealers, Technicians, Inventory, Warranty, Settings
export const pageSpecificAutoDict: Record<string, string> = {
  // Dealers
  'Dealers': 'डीलर',
  'Dealer Code': 'डीलर कोड',
  'Dealer Name': 'डीलर का नाम',
  'Phone': 'फ़ोन',
  'Registered on': 'पंजीकृत तारीख',
  'All Cities': 'सभी शहर',
  'Select a city': 'एक शहर चुनें',
  'Total Dealers': 'कुल डीलर',
  'Active Dealers': 'सक्रिय डीलर',

  // Technicians
  'Technicians': 'तकनीशियन',
  'Total Technicians': 'कुल तकनीशियन',
  'Active Technicians': 'सक्रिय तकनीशियन',

  // Inventory
  'Inventory': 'इन्वेंटरी',
  'Total Stock Rows': 'कुल स्टॉक पंक्तियाँ',
  'Part Code': 'पार्ट कोड',
  'Part Name': 'पार्ट नाम',
  'Category': 'श्रेणी',
  'Stock': 'स्टॉक',
  'Unit Price': 'इकाई कीमत',
  'Value': 'मूल्य',
  'In Stock': 'स्टॉक में',
  'Low Stock': 'कम स्टॉक',
  'Out of Stock': 'स्टॉक नहीं है',

  // Warranty Claims
  'Warranty Claims': 'वारंटी दावे',
  'Warranty claims': 'वारंटी दावे',
  'Track and manage warranty claims efficiently': 'वारंटी दावों को कुशलतापूर्वक ट्रैक और प्रबंधित करें',
  'Claim lifecycle': 'दावे का जीवनचक्र',
  'Claim received': 'दावा प्राप्त',
  'Verification in progress': 'सत्यापन जारी है',
  'Claim approved': 'दावा स्वीकृत',
  'Claim completed': 'दावा पूरा',
  'Search by chassis number or claim ID': 'चेसिस नंबर या दावा आईडी से खोजें',
  'Claim ID': 'दावा आईडी',
  'Chassis No.': 'चेसिस संख्या',
  'Component': 'घटक',
  'Dealer': 'डीलर',
  'Submitted on': 'सबमिट की तारीख',
  'Claim #': 'दावा #',
  'Submitted': 'सबमिट किया गया',
  'Resolved': 'सुलझा गया',
  'View details →': 'विवरण देखें →',
  'Search claims...': 'दावे खोजें...',
  'No claims match your search.': 'आपकी खोज से कोई दावा मेल नहीं खाता।',
  'File a new warranty claim': 'नया वारंटी दावा दर्ज करें',
  'Chassis number': 'चेसिस नंबर',
  'Remarks': 'टिप्पणियाँ',
  'Describe the issue': 'समस्या का वर्णन करें',
  'Submit claim': 'दावा सबमिट करें',
  'Submitting...': 'सबमिट किया जा रहा है...',

  // Warranty Check
  'Smart warranty check': 'स्मार्ट वारंटी चेक',
  'Scan or enter a chassis number to check warranty status and claim eligibility': 'वारंटी स्थिति और दावे की पात्रता जांचने के लिए चेसिस नंबर स्कैन या दर्ज करें',
  'Enter chassis number': 'चेसिस नंबर दर्ज करें',
  'Check warranty': 'वारंटी जांचें',
  'Checking...': 'जाँच हो रही है...',
  'Warranty status — ': 'वारंटी स्थिति — ',
  'Claim eligibility & required documents': 'दावा पात्रता और आवश्यक दस्तावेज',
  'Eligible': 'पात्र',
  'Not eligible': 'पात्र नहीं',
  'Required documents:': 'आवश्यक दस्तावेज:',
  'No previous claims for this vehicle.': 'इस वाहन के लिए कोई पिछला दावा नहीं है।',

  // Settings
  'Settings': 'सेटिंग्स',
  'Manage your account, preferences and system configuration': 'अपने खाते, प्राथमिकताओं और सिस्टम कॉन्फ़िगरेशन को प्रबंधित करें',
  'General': 'सामान्य',
  'Users & Roles': 'उपयोगकर्ता और भूमिकाएँ',
  'Notifications': 'सूचनाएँ',
  'Security': 'सुरक्षा',
  'Integrations': 'इंटीग्रेशन',
  'System': 'सिस्टम',
  'Company Profile': 'कंपनी प्रोफ़ाइल',
  'Not connected — display only': 'कनेक्ट नहीं — केवल प्रदर्शन',
  'Company Name': 'कंपनी का नाम',
  'Address': 'पता',
  'City': 'शहर',
  'State': 'राज्य',
  'All Users': 'सभी उपयोगकर्ता',
  'Search by name, email, or phone...': 'नाम, ईमेल या फ़ोन से खोजें...',
  'Loading users...': 'उपयोगकर्ता लोड हो रहे हैं...',
};
 
// Additional strings for Vehicles, Jobcards, Analytics, Inventory pages
Object.assign(autoDict, {
  // Vehicles page
  'Register a vehicle': 'वाहन पंजीकृत करें',
  'Register vehicle →': 'वाहन पंजीकृत करें →',
  'Vehicle Registration': 'वाहन पंजीकरण',
  'Registered vehicles': 'पंजीकृत वाहन',
  'Vehicle Information': 'वाहन जानकारी',
  'Battery & Motor': 'बैटरी और मोटर',
  'Additional Details': 'अतिरिक्त विवरण',
  'Review & Submit': 'समीक्षा और सबमिट',
  'Customer name *': 'ग्राहक का नाम *',
  'Customer phone *': 'ग्राहक फ़ोन *',
  'Customer address': 'ग्राहक का पता',
  'Dealer *': 'डीलर *',
  'Vehicle model *': 'वाहन मॉडल *',
  'Vehicle colour *': 'वाहन रंग *',
  'Purchase date *': 'खरीदने की तारीख *',
  'Chassis number *': 'चेसिस संख्या *',
  'Motor number *': 'मोटर नंबर *',
  'Battery serial number *': 'बैटरी सीरियल नंबर *',
  'Charger serial number': 'चार्जर सीरियल नंबर',
  'Customer': 'ग्राहक',
  'Phone': 'फ़ोन',
  'Chassis No.': 'चेसिस संख्या',
  'Colour': 'रंग',
  'Purchase date': 'खरीद की तारीख',
  'Vehicle model': 'वाहन मॉडल',
  'QR Code': 'क्यूआर कोड',
  'No vehicles found.': 'कोई वाहन नहीं मिला।',
  'Showing {filtered.length} of {vehicles.length} entries': 'प्रदर्शित {filtered.length} में से {vehicles.length} प्रविष्टियाँ',

  // Jobcards page
  'Job cards / complaints': 'जॉब कार्ड / शिकायतें',
  'Job cards / Complaints': 'जॉब कार्ड / शिकायतें',
  'Track, manage and resolve customer complaints & service jobs': 'ग्राहक शिकायतों और सेवा जॉब्स को ट्रैक, प्रबंधित और हल करें',
  'Total Job Cards': 'कुल जॉब कार्ड',
  'In Progress': 'प्रगति में',
  'SLA Breaches': 'एसएलए उल्लंघन',
  'Create job card / log a complaint': 'जॉब कार्ड बनाएं / शिकायत दर्ज करें',
  'Vehicle (chassis number) *': 'वाहन (चेसिस संख्या) *',
  'Describe the complaint *': 'शिकायत का वर्णन करें *',
  'Paid service': 'भुगतान सेवा',
  'Warranty claim': 'वारंटी दावा',
  'Priority': 'प्राथमिकता',
  'Which part (optional)': 'कौन सा भाग (वैकल्पिक)',
  "What's the problem (optional)": 'समस्या क्या है (वैकल्पिक)',
  'Photos (optional, max 5)': 'फोटो (वैकल्पिक, अधिकतम 5)',
  'Create job card →': 'जॉब कार्ड बनाएं →',
  'All job cards': 'सभी जॉब कार्ड',
  'No job cards found.': 'कोई जॉब कार्ड नहीं मिला।',

  // Analytics page
  'Analytics': 'एनालिटिक्स',
  'Real-time insights and performance overview of your EV service operations.': 'आपके ईवी सेवा संचालन का रियल-टाइम इनसाइट और प्रदर्शन अवलोकन।',
  'From': 'से',
  'To': 'तक',
  'Apply': 'लागू करें',
  'Export CSV': 'सीएसवी निर्यात करें',
  'Total Vehicles': 'कुल वाहन',
  'Total Jobs': 'कुल जॉब्स',
  'Avg. Resolution Time': 'औसत समाधान समय',
  'Completed Jobs': 'पूर्ण जॉब्स',
  'Revenue (parts)': 'राजस्व (पार्ट्स)',
  'Avg Customer Rating': 'औसत ग्राहक रेटिंग',
  'Avg Technician Rating': 'औसत तकनीशियन रेटिंग',
  'vs last period': 'पिछली अवधि की तुलना में',
  'review': 'समीक्षा',
  'reviews': 'समीक्षाएँ',
  'Jobs Trend Over Time (last 7 days)': 'समय के साथ जॉब्स का रुझान (पिछले 7 दिन)',
  'Jobs by Status': 'स्थिति के अनुसार जॉब्स',
  'Performance Overview': 'प्रदर्शन अवलोकन',
  'Bar height = total jobs registered that day': 'बार ऊंचाई = उस दिन दर्ज कुल जॉब्स',

  // Inventory page additions
  'All Categories': 'सभी श्रेणियाँ',
  'Showing X to Y of Z items': 'प्रदर्शित X से Y में से Z आइटम',
  'subtitle text': 'उपशीर्षक पाठ',
});

// Merge page-specific entries into the main autoDict so AutoTranslate picks them up.
Object.assign(autoDict, pageSpecificAutoDict);