export const NAV_ITEMS = [
  { label: 'Dashboard', href: '/', key: 'dashboard' as const },
  { label: 'Vehicle Registration', href: '/vehicles', key: 'vehicles' as const },
  { label: 'Job Cards / Complaints', href: '/jobcards', key: 'jobcards' as const },
  { label: 'Warranty Claims', href: '/warranty-claims', key: 'warrantyClaims' as const },
  { label: 'Warranty Check', href: '/warranty-check', key: 'warrantyCheck' as const },
  { label: 'Dealers', href: '/dealers', key: 'dealers' as const },
  { label: 'Technicians', href: '/technicians', key: 'technicians' as const },
  { label: 'Live Map', href: '/live-map', key: 'liveMap' as const },
  { label: 'Pan India', href: '/pan-india', key: 'panIndia' as const },
  { label: 'WhatsApp Inbox', href: '/whatsapp-inbox', key: 'whatsappInbox' as const },
  { label: 'Inventory', href: '/inventory', key: 'inventory' as const },
  { label: 'Analytics', href: '/analytics', key: 'analytics' as const },
  { label: 'Fraud Alerts', href: '/fraud-alerts', key: 'fraudAlerts' as const },
  { label: 'Settings', href: '/settings', key: 'settings' as const },
];